//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPresentacion.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/SBK.Servicios")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        WebPresentacion.ServiceReference1.CompositeType GetDataUsingDataContract(WebPresentacion.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarRegistro", ReplyAction="http://tempuri.org/IService1/ListarRegistroResponse")]
        string ListarRegistro();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarUsuario", ReplyAction="http://tempuri.org/IService1/ListarUsuarioResponse")]
        string ListarUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarRegistroUser", ReplyAction="http://tempuri.org/IService1/ListarRegistroUserResponse")]
        string ListarRegistroUser(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarLogin", ReplyAction="http://tempuri.org/IService1/ValidarLoginResponse")]
        bool ValidarLogin(string LOGusuario, string LOGpassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ID_desde_LogUser", ReplyAction="http://tempuri.org/IService1/ID_desde_LogUserResponse")]
        int ID_desde_LogUser(string LOGusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nombre_desde_LogUser", ReplyAction="http://tempuri.org/IService1/Nombre_desde_LogUserResponse")]
        string Nombre_desde_LogUser(string LOGusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Read", ReplyAction="http://tempuri.org/IService1/ReadResponse")]
        string Read(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Create", ReplyAction="http://tempuri.org/IService1/CreateResponse")]
        bool Create(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update", ReplyAction="http://tempuri.org/IService1/UpdateResponse")]
        bool Update(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete", ReplyAction="http://tempuri.org/IService1/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/R_CantidadUsuarios", ReplyAction="http://tempuri.org/IService1/R_CantidadUsuariosResponse")]
        string R_CantidadUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/R_CantidadEstudiante", ReplyAction="http://tempuri.org/IService1/R_CantidadEstudianteResponse")]
        string R_CantidadEstudiante();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/R_CantidadFuncionario", ReplyAction="http://tempuri.org/IService1/R_CantidadFuncionarioResponse")]
        string R_CantidadFuncionario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/R_UsuarioMasActivo", ReplyAction="http://tempuri.org/IService1/R_UsuarioMasActivoResponse")]
        string R_UsuarioMasActivo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/R_CantidadRegistrosMaxUser", ReplyAction="http://tempuri.org/IService1/R_CantidadRegistrosMaxUserResponse")]
        string R_CantidadRegistrosMaxUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/R_PromedioDeRegistros", ReplyAction="http://tempuri.org/IService1/R_PromedioDeRegistrosResponse")]
        string R_PromedioDeRegistros();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebPresentacion.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebPresentacion.ServiceReference1.IService1>, WebPresentacion.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public WebPresentacion.ServiceReference1.CompositeType GetDataUsingDataContract(WebPresentacion.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public string ListarRegistro() {
            return base.Channel.ListarRegistro();
        }
        
        public string ListarUsuario() {
            return base.Channel.ListarUsuario();
        }
        
        public string ListarRegistroUser(int _id) {
            return base.Channel.ListarRegistroUser(_id);
        }
        
        public bool ValidarLogin(string LOGusuario, string LOGpassword) {
            return base.Channel.ValidarLogin(LOGusuario, LOGpassword);
        }
        
        public int ID_desde_LogUser(string LOGusuario) {
            return base.Channel.ID_desde_LogUser(LOGusuario);
        }
        
        public string Nombre_desde_LogUser(string LOGusuario) {
            return base.Channel.Nombre_desde_LogUser(LOGusuario);
        }
        
        public string Read(int id) {
            return base.Channel.Read(id);
        }
        
        public bool Create(string id) {
            return base.Channel.Create(id);
        }
        
        public bool Update(string id) {
            return base.Channel.Update(id);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public string R_CantidadUsuarios() {
            return base.Channel.R_CantidadUsuarios();
        }
        
        public string R_CantidadEstudiante() {
            return base.Channel.R_CantidadEstudiante();
        }
        
        public string R_CantidadFuncionario() {
            return base.Channel.R_CantidadFuncionario();
        }
        
        public string R_UsuarioMasActivo() {
            return base.Channel.R_UsuarioMasActivo();
        }
        
        public string R_CantidadRegistrosMaxUser() {
            return base.Channel.R_CantidadRegistrosMaxUser();
        }
        
        public string R_PromedioDeRegistros() {
            return base.Channel.R_PromedioDeRegistros();
        }
    }
}
